### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by alex-nexus** [tebayoso/ipsymusic#1]
how would you approach in terms of authentication?

**Comment by tebayoso** [comment]
Well this depends on where is this api going to be. I can think on some scenarios:

1. It's a microservice and the consumer is a front-facing application, in this scenario the authentication/authorization should be handled by a RBAC/OAUTH layer/server which will be filtering access to the resources based on the user/service requesting the information/performing the action.
2. It's a front-facing accessible API, like an API for mobile devices, frontend applications or data service for consumers (Open API). In this scenario we can use both the authentication/Authorization layer in order to avoid inserting this logic in the app/microservice. Or if the API is going to move into a monolothic application (which shouldn't need to be a bad decision in early stages or in small teams), then we will introduce a user management, and the user authenticatión in the controller lifecycle. Probably using a token authentication in the request, and a horizontal permission based access in the backend (Pundit, Cancancan, etc...).
